"""initial schema

Revision ID: a628cb408ee0
Revises: 
Create Date: 2026-08-31 18:16:49.688382

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a628cb408ee0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ENUMERATING', 'PROBING', 'PORT_SCANNING', 'CHECKING_TAKEOVER', 'SCANNING_JS', 'TRIAGING', 'COMPLETED', 'FAILED', name='scanstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('artifacts_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_jobs_domain_id'), 'scan_jobs', ['domain_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_status'), 'scan_jobs', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('ai_model_used', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_domain_id'), 'reports', ['domain_id'], unique=False)
    op.create_index(op.f('ix_reports_scan_job_id'), 'reports', ['scan_job_id'], unique=True)
    op.create_table('subdomains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_addresses', sa.JSON(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('http_title', sa.String(length=512), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('open_ports', sa.JSON(), nullable=True),
    sa.Column('takeover_candidate', sa.Boolean(), nullable=False),
    sa.Column('takeover_fingerprint', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subdomains_domain_id'), 'subdomains', ['domain_id'], unique=False)
    op.create_index(op.f('ix_subdomains_hostname'), 'subdomains', ['hostname'], unique=False)
    op.create_index(op.f('ix_subdomains_scan_job_id'), 'subdomains', ['scan_job_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('subdomain_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('SUBDOMAIN_TAKEOVER', 'OPEN_PORT', 'EXPOSED_SECRET', 'EXPOSED_ENDPOINT', 'MISCONFIGURATION', name='findingcategory'), nullable=False),
    sa.Column('source_tool', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('raw_evidence', sa.JSON(), nullable=True),
    sa.Column('ai_verdict', sa.Enum('PENDING', 'TRUE_POSITIVE', 'FALSE_POSITIVE', 'NEEDS_REVIEW', name='aiverdict'), nullable=False),
    sa.Column('ai_severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('ai_reproduction_steps', sa.Text(), nullable=True),
    sa.Column('ai_remediation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('triaged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subdomain_id'], ['subdomains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_ai_verdict'), 'findings', ['ai_verdict'], unique=False)
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_index(op.f('ix_findings_domain_id'), 'findings', ['domain_id'], unique=False)
    op.create_index(op.f('ix_findings_scan_job_id'), 'findings', ['scan_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_scan_job_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_domain_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_index(op.f('ix_findings_ai_verdict'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_subdomains_scan_job_id'), table_name='subdomains')
    op.drop_index(op.f('ix_subdomains_hostname'), table_name='subdomains')
    op.drop_index(op.f('ix_subdomains_domain_id'), table_name='subdomains')
    op.drop_table('subdomains')
    op.drop_index(op.f('ix_reports_scan_job_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_domain_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_scan_jobs_status'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_domain_id'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
